#!/bin/bash
LOCAL_SOURCE_DIR=/tmp/src
WEBTOB_ROOT=/root/webtob
echo "---> Installing application source..."

# apps files
if [ -d $LOCAL_SOURCE_DIR/docs ]; then
  echo "Copying Application files from webapps of git project..."
  cp -Rf $LOCAL_SOURCE_DIR/docs/* $WEBTOB_ROOT/docs/
fi

# configuration files
if [ -d $LOCAL_SOURCE_DIR/config ]; then
  echo "Copying config files from conf of git project..."
  cp -Rf $LOCAL_SOURCE_DIR/config/* $WEBTOB_ROOT/config/
fi

